version: "3"

services:

    #############################
    # Database
    #############################
    database:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: jp
          MYSQL_DATABASE: jpproject
          MYSQL_PASSWORD: 10203040
    
    #############################
    # Server SSO
    #############################
    sso:
        image: "jpproject-sso"
        build: 
          context: .
          dockerfile: sso.dockerfile
        ports:
            - "5001:5001"
            - "5000:5000"
        links:
            - database
        depends_on:
            - database
        environment: 
            DATABASE_TYPE: "MySql"
            CUSTOMCONNSTR_DATABASE_CONNECTION: "server=database,port=3306;database=jpproject;user=jp;password=10203040"
            ASPNETCORE_ENVIRONMENT: "Development"
            # ISSUER_URI: "http://localhost:5000"
            ASPNETCORE_Kestrel__Certificates__Default__Password: ".pxCpE]yttwC&b&hriw#,7K^_}A7xezRH3=EisJKn3]8.H}^Unzd+ebw]zzv_=d3"
            ASPNETCORE_Kestrel__Certificates__Default__Path: "/root/.dotnet/https/jpproject.pfx"
            ASPNETCORE_URLS: https://+:5000;http://+:5001

    #############################
    # Management API
    #############################
    jpproject-api:
        container_name: jpproject-api
        build: 
          context: .
          dockerfile: user-management.dockerfile
        ports:
            - "5003:5003"
            - "5002:5002"
        depends_on:
            - database
        environment: 
            DATABASE_TYPE: "MySql"
            CUSTOMCONNSTR_DATABASE_CONNECTION: "server=database,port=3306;database=jpproject;user=jp;password=10203040"
            ASPNETCORE_ENVIRONMENT: "Development"
            AUTHORITY: "http://localhost:5000"
            ASPNETCORE_URLS: "https://+:5003;http://+:5002"

    #############################
    # User management UI
    #############################
    user-management-ui:
        container_name: jpproject-user-management-ui
        build: 
          context: .
          dockerfile: ui-user-management.dockerfile
        ports:
            - 4300:80
