# BUG's at SSL and Issuer Validation
# SSL bug: https://github.com/dotnet/corefx/issues/22996 and https://github.com/dotnet/corefx/issues/31034
# There are a mismatch between Angular Isser Name and Api Issuer Name, so it cant validate it inside docker ambient.
    version: "3"
    
    networks:
        jpproject_network:
          driver: bridge
          ipam:
            driver: default
            config:
              - subnet: 172.20.0.0/16
    services:

        #############################
        # Database
        #############################
        database:
            image: "microsoft/mssql-server-linux"

            environment:
                SA_PASSWORD: "@Password1"
                ACCEPT_EULA: "Y"

            ports:
                - "44274:1433"
            
            healthcheck:
                test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "Password1", "-Q", "select 1" ]
                interval: 1s
                retries: 30

            networks:
                jpproject_network:
                    ipv4_address: 172.20.0.5
        #############################
        # Server SSO
        #############################
        sso:
            image: "jpproject-sso"

            build: 
              context: .
              dockerfile: sso.dockerfile

            ports:
                - "5001:5001"
                - "5000:5000"

            depends_on:
                - database
            
            environment: 
                DATABASE_CONNECTION: "Server=database,1433;Initial Catalog=JpProject;Persist Security Info=False;User ID=sa;Password=@Password1;MultipleActiveResultSets=False;Connection Timeout=30;"
                ASPNETCORE_ENVIRONMENT: "Development"
                # ISSUER_URI: "http://localhost:5000"
                ASPNETCORE_Kestrel__Certificates__Default__Password: ".pxCpE]yttwC&b&hriw#,7K^_}A7xezRH3=EisJKn3]8.H}^Unzd+ebw]zzv_=d3"
                ASPNETCORE_Kestrel__Certificates__Default__Path: "/root/.dotnet/https/jpproject.pfx"
                ASPNETCORE_URLS: http://+:5000;http://+:5001

            networks:
                jpproject_network:
                    ipv4_address: 172.20.0.6

        #############################
        # Management API
        #############################
        user-management-api:
            container_name: jpproject-user_management_api
            build: 
              context: .
              dockerfile: user-management.dockerfile

            ports:
                - "5003:443"
                - "5002:80"

            depends_on:
                - database
                - sso

            environment: 
                SQLSERVER_CONNECTION: "Server=database,1433;Initial Catalog=JpProject;Persist Security Info=False;User ID=sa;Password=@Password1;MultipleActiveResultSets=False;Connection Timeout=30;"
                ASPNETCORE_ENVIRONMENT: "Development"
                AUTHORITY: "http://localhost:5000"
                ASPNETCORE_Kestrel__Certificates__Default__Password: ".pxCpE]yttwC&b&hriw#,7K^_}A7xezRH3=EisJKn3]8.H}^Unzd+ebw]zzv_=d3"
                ASPNETCORE_Kestrel__Certificates__Default__Path: "/root/.dotnet/https/jpproject.pfx"
                ASPNETCORE_URLS: "https://+:443;http://+:80"
                VALIDATE_ISSUER: "false"

            networks:
                jpproject_network:
                    ipv4_address: 172.20.0.7

        #############################
        # User management UI
        #############################
        user-management-ui:
            container_name: jpproject-user-management-ui

            build: 
              context: .
              dockerfile: ui-user-management.dockerfile

            ports:
                - 4200:80

            networks:
                jpproject_network:
                    ipv4_address: 172.20.0.8
