    version: "3"
    services:

        #############################
        # Database
        #############################
        database:
            image: "microsoft/mssql-server-linux"

            environment:
                SA_PASSWORD: "@Password1"
                ACCEPT_EULA: "Y"

            ports:
                - "44274:1433"
            
            healthcheck:
                test: [ "CMD", "sqlcmd", "-U", "sa", "-P", "Password1", "-Q", "select 1" ]
                interval: 1s
                retries: 30
              
        #############################
        # Server SSO
        #############################
        sso:
            image: "jpproject-sso"

            build: 
              context: .
              dockerfile: sso.dockerfile

            ports:
                - "5000:5000"

            depends_on:
                - database
            
            environment: 
                SQLSERVER_CONNECTION: "Server=database,1433;Initial Catalog=JpProject;Persist Security Info=False;User ID=sa;Password=@Password1;MultipleActiveResultSets=False;Connection Timeout=30;"
                ASPNETCORE_ENVIRONMENT: "Development"
                ISSUER_URI: "http://localhost:5000"
                # PUBLIC_URI: "http://localhost:5000"

        #############################
        # Management API
        #############################
        user-management-api:
            container_name: jpproject-user_management_api
            build: 
              context: .
              dockerfile: user-management.dockerfile

            ports:
                - "5003:5003"

            depends_on:
                - database
                - sso

            environment: 
                SQLSERVER_CONNECTION: "Server=database,1433;Initial Catalog=JpProject;Persist Security Info=False;User ID=sa;Password=@Password1;MultipleActiveResultSets=False;Connection Timeout=30;"
                ASPNETCORE_ENVIRONMENT: "Development"
                AUTHORITY: "http://sso:5000"
                VALIDATE_ISSUER: "false"

        #############################
        # User management UI
        #############################
        user-management-ui:
            container_name: jpproject-user-management-ui

            build: 
              context: .
              dockerfile: ui-user-management.dockerfile

            ports:
                - 4200:80